import type { User, WorkOrder } from './types'

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Marcus Chen',
    email: 'admin@fieldops.io',
    role: 'ADMIN',
    avatar: 'MC',
  },
  {
    id: 'u2',
    name: 'Sarah Okafor',
    email: 'sarah@fieldops.io',
    role: 'TECHNICIAN',
    avatar: 'SO',
  },
  {
    id: 'u3',
    name: 'James Rivera',
    email: 'james@fieldops.io',
    role: 'TECHNICIAN',
    avatar: 'JR',
  },
  {
    id: 'u4',
    name: 'Priya Nair',
    email: 'priya@fieldops.io',
    role: 'TECHNICIAN',
    avatar: 'PN',
  },
]

export const MOCK_CREDENTIALS = [
  { email: 'admin@fieldops.io', password: 'admin123', userId: 'u1' },
  { email: 'sarah@fieldops.io', password: 'tech123', userId: 'u2' },
]

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-1042',
    title: 'HVAC Unit Failure — Building 3 East Wing',
    description:
      'Compressor seized overnight. Tenant reports complete cooling loss. Requires full diagnostic and likely compressor swap. Parts on order from HVAC Supply Co.',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    assignedTechnician: USERS[1],
    version: 4,
    checklist: [
      { id: 'c1', label: 'Shut down power to unit', completed: true },
      { id: 'c2', label: 'Run full diagnostic scan', completed: true },
      { id: 'c3', label: 'Order replacement compressor', completed: true },
      { id: 'c4', label: 'Install new compressor', completed: false },
      { id: 'c5', label: 'Recharge refrigerant', completed: false },
      { id: 'c6', label: 'Test full system operation', completed: false },
      { id: 'c7', label: 'Sign off with building manager', completed: false },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-18T08:14:22Z',
      },
      {
        id: 'a2',
        user: 'Marcus Chen',
        action: 'Assigned to Sarah Okafor',
        timestamp: '2026-07-18T08:17:03Z',
      },
      {
        id: 'a3',
        user: 'Sarah Okafor',
        action: 'Started work order',
        prevStatus: 'OPEN',
        newStatus: 'IN_PROGRESS',
        timestamp: '2026-07-18T09:02:45Z',
      },
      {
        id: 'a4',
        user: 'Sarah Okafor',
        action: 'Updated checklist (3 items completed)',
        timestamp: '2026-07-19T14:33:11Z',
      },
    ],
    createdAt: '2026-07-18T08:14:22Z',
    updatedAt: '2026-07-19T14:33:11Z',
  },
  {
    id: 'WO-1041',
    title: 'Elevator Hydraulic Leak — Tower A',
    description:
      'Elevator #2 hydraulic fluid leaking at base of piston assembly. Elevator taken out of service. Requires immediate inspection and seal replacement.',
    priority: 'HIGH',
    status: 'OPEN',
    assignedTechnician: USERS[2],
    version: 1,
    checklist: [
      { id: 'c1', label: 'Isolate elevator from service', completed: false },
      { id: 'c2', label: 'Identify leak source', completed: false },
      { id: 'c3', label: 'Replace hydraulic seals', completed: false },
      { id: 'c4', label: 'Refill hydraulic fluid', completed: false },
      { id: 'c5', label: 'Test pressure integrity', completed: false },
      { id: 'c6', label: 'Safety certification sign-off', completed: false },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-20T10:45:00Z',
      },
    ],
    createdAt: '2026-07-20T10:45:00Z',
    updatedAt: '2026-07-20T10:45:00Z',
  },
  {
    id: 'WO-1040',
    title: 'Fire Suppression System Inspection — Parking Garage',
    description:
      'Annual mandatory inspection of sprinkler system in underground parking levels P1–P3. All heads must be tested and pressure verified.',
    priority: 'MEDIUM',
    status: 'DONE',
    assignedTechnician: USERS[1],
    version: 3,
    checklist: [
      { id: 'c1', label: 'Review previous inspection report', completed: true },
      { id: 'c2', label: 'Test all sprinkler heads P1', completed: true },
      { id: 'c3', label: 'Test all sprinkler heads P2', completed: true },
      { id: 'c4', label: 'Test all sprinkler heads P3', completed: true },
      { id: 'c5', label: 'Verify main line pressure', completed: true },
      { id: 'c6', label: 'Submit compliance report', completed: true },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-10T09:00:00Z',
      },
      {
        id: 'a2',
        user: 'Sarah Okafor',
        action: 'Started inspection',
        prevStatus: 'OPEN',
        newStatus: 'IN_PROGRESS',
        timestamp: '2026-07-15T08:30:00Z',
      },
      {
        id: 'a3',
        user: 'Sarah Okafor',
        action: 'Completed all checklist items',
        timestamp: '2026-07-15T16:45:00Z',
      },
      {
        id: 'a4',
        user: 'Sarah Okafor',
        action: 'Marked as completed',
        prevStatus: 'IN_PROGRESS',
        newStatus: 'DONE',
        timestamp: '2026-07-15T16:50:22Z',
      },
    ],
    createdAt: '2026-07-10T09:00:00Z',
    updatedAt: '2026-07-15T16:50:22Z',
  },
  {
    id: 'WO-1039',
    title: 'Roof Drainage Blockage — South Block',
    description:
      'Multiple downspouts blocked causing pooling on flat roof. Risk of water ingress. Immediate clearance required before weekend rain forecast.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedTechnician: USERS[3],
    version: 2,
    checklist: [
      { id: 'c1', label: 'Access roof safely (ladder/harness)', completed: true },
      { id: 'c2', label: 'Identify all blocked outlets', completed: true },
      { id: 'c3', label: 'Clear debris from downspouts', completed: false },
      { id: 'c4', label: 'Test water flow', completed: false },
      { id: 'c5', label: 'Install gutter guards on risk areas', completed: false },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-21T07:20:00Z',
      },
      {
        id: 'a2',
        user: 'Priya Nair',
        action: 'Accepted and started',
        prevStatus: 'OPEN',
        newStatus: 'IN_PROGRESS',
        timestamp: '2026-07-21T09:15:00Z',
      },
    ],
    createdAt: '2026-07-21T07:20:00Z',
    updatedAt: '2026-07-21T09:15:00Z',
  },
  {
    id: 'WO-1038',
    title: 'Generator Maintenance — Data Center',
    description:
      'Quarterly preventive maintenance on backup generator. Oil change, filter replacement, load bank test, and transfer switch inspection.',
    priority: 'MEDIUM',
    status: 'OPEN',
    assignedTechnician: USERS[2],
    version: 1,
    checklist: [
      { id: 'c1', label: 'Check coolant level and condition', completed: false },
      { id: 'c2', label: 'Change engine oil and filter', completed: false },
      { id: 'c3', label: 'Replace fuel filter', completed: false },
      { id: 'c4', label: 'Inspect belts and hoses', completed: false },
      { id: 'c5', label: 'Run load bank test (30 min)', completed: false },
      { id: 'c6', label: 'Test automatic transfer switch', completed: false },
      { id: 'c7', label: 'Log results and file report', completed: false },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-22T11:00:00Z',
      },
    ],
    createdAt: '2026-07-22T11:00:00Z',
    updatedAt: '2026-07-22T11:00:00Z',
  },
  {
    id: 'WO-1037',
    title: 'Electrical Panel Upgrade — Unit 4B',
    description:
      'Tenant requesting 200A panel upgrade from existing 100A service. Permits obtained. Coordination with utility company for temporary disconnect needed.',
    priority: 'LOW',
    status: 'DONE',
    assignedTechnician: USERS[3],
    version: 5,
    checklist: [
      { id: 'c1', label: 'Verify permits on file', completed: true },
      { id: 'c2', label: 'Schedule utility disconnect', completed: true },
      { id: 'c3', label: 'Install new 200A panel', completed: true },
      { id: 'c4', label: 'Re-wire circuits to new panel', completed: true },
      { id: 'c5', label: 'Restore utility power', completed: true },
      { id: 'c6', label: 'Final inspection sign-off', completed: true },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-08T09:00:00Z',
      },
      {
        id: 'a2',
        user: 'Priya Nair',
        action: 'Started work',
        prevStatus: 'OPEN',
        newStatus: 'IN_PROGRESS',
        timestamp: '2026-07-14T07:00:00Z',
      },
      {
        id: 'a3',
        user: 'Priya Nair',
        action: 'Completed successfully',
        prevStatus: 'IN_PROGRESS',
        newStatus: 'DONE',
        timestamp: '2026-07-14T15:30:00Z',
      },
    ],
    createdAt: '2026-07-08T09:00:00Z',
    updatedAt: '2026-07-14T15:30:00Z',
  },
  {
    id: 'WO-1036',
    title: 'Plumbing Repair — Lobby Restrooms',
    description:
      'Both men and women restrooms experiencing low water pressure. Suspect partially closed isolation valve in basement riser. Immediate investigation required.',
    priority: 'MEDIUM',
    status: 'OPEN',
    assignedTechnician: USERS[1],
    version: 1,
    checklist: [
      { id: 'c1', label: 'Inspect basement riser valves', completed: false },
      { id: 'c2', label: 'Check pressure at fixtures', completed: false },
      { id: 'c3', label: 'Identify and repair fault', completed: false },
      { id: 'c4', label: 'Verify pressure restoration', completed: false },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-23T06:45:00Z',
      },
    ],
    createdAt: '2026-07-23T06:45:00Z',
    updatedAt: '2026-07-23T06:45:00Z',
  },
  {
    id: 'WO-1035',
    title: 'Security Camera Offline — East Entrance',
    description:
      'Camera 7 at east entrance has been offline for 48 hours. Network switch port may have failed. Check cabling and PoE switch configuration.',
    priority: 'HIGH',
    status: 'DONE',
    assignedTechnician: USERS[2],
    version: 2,
    checklist: [
      { id: 'c1', label: 'Check physical cable connections', completed: true },
      { id: 'c2', label: 'Test PoE port with another device', completed: true },
      { id: 'c3', label: 'Replace failed PoE switch port', completed: true },
      { id: 'c4', label: 'Verify camera feed in VMS', completed: true },
    ],
    auditLog: [
      {
        id: 'a1',
        user: 'Marcus Chen',
        action: 'Created work order',
        newStatus: 'OPEN',
        timestamp: '2026-07-19T14:00:00Z',
      },
      {
        id: 'a2',
        user: 'James Rivera',
        action: 'Investigated and resolved',
        prevStatus: 'OPEN',
        newStatus: 'IN_PROGRESS',
        timestamp: '2026-07-20T09:00:00Z',
      },
      {
        id: 'a3',
        user: 'James Rivera',
        action: 'Completed repair',
        prevStatus: 'IN_PROGRESS',
        newStatus: 'DONE',
        timestamp: '2026-07-20T11:30:00Z',
      },
    ],
    createdAt: '2026-07-19T14:00:00Z',
    updatedAt: '2026-07-20T11:30:00Z',
  },
]
